### ISSUE TITLE
Error 400: CannotParseRequest - Incorrectly formatted request with Core Instance on unchanged setup

### ISSUE THREAD

**Issue by arioberek** [statickidz/dokploy-oci-free#1]
I encountered an issue when trying to launch an instance using `oci_core_instance`. I received the following error messages during the `LaunchInstance` operation:

```
Error 1:
Error: 400-CannotParseRequest, Incorrectly formatted request. Please refer to our documentation for help.
Suggestion: Please retry or contact support for help with service: Core Instance
Request Target: POST https://iaas.sa-saopaulo-1.oraclecloud.com/.../instances
```

```
Error 2:
Error: 400-CannotParseRequest, Incorrectly formatted request. Please refer to our documentation for help.
Suggestion: Please retry or contact support for help with service: Core Instance
Request Target: POST https://iaas.sa-saopaulo-1.oraclecloud.com/.../instances
```

Both errors occurred during the `LaunchInstance` operation, and the setup remains unchanged.

---

### Error Details:
- **Provider Version**: 6.14.0 (Released on 2024-10-20)
- **Service**: Core Instance
- **Operation Name**: LaunchInstance
- **Request Target**: POST to the OCI API for instance launch

---

### Affected Resources:
1. `oci_core_instance.dokploy_main` (line 2 in `main.tf`)
2. `oci_core_instance.dokploy_worker[0]` (line 88 in `main.tf`)

---

### Steps to Reproduce:
1. Clone the repository: [dokploy-oci-free](https://github.com/statickidz/dokploy-oci-free)
2. Ensure the latest version of the provider (`6.14.0`) is being used.
3. Apply the Terraform configuration to launch the OCI instances.

---

### Expected Behavior:
Instances should launch without issues, as the setup remains unchanged.

---

### Actual Behavior:
The process fails with the error `400-CannotParseRequest`.

---

### Additional Information:
- **Documentation Link**: [Core Instance Resource](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance)
- **API Reference**: [API LaunchInstance](https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance)

No recent changes were made to the code, and the setup worked previously with the same configuration.

**Comment by statickidz** [comment]
This is not fully tested to run with terraform isolated, the way it's build is to launch it as a stack through the resource manager with the deploy button or cloning the repo and linking from your own copy.

[![Deploy to Oracle Cloud](https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg)](https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://github.com/statickidz/dokploy-oci-free/archive/refs/heads/main.zip)

I may add support for that but it's not planned atm.
